[General]
LogFile = "/tmp/go_connect.log"

[DB]
Api = "http://chef.zenvia360.com:4567/allnodes"
RequestTimeout = 5
ConnectonTimeout = 1 
Path = "/Users/jorge.flores/nodes.db"
MaxAge = 30

[CSSH]
Enable = false
Path = "/Users/jorge.flores/csshx/csshX"

