[General]
LogFile = "/tmp/go_connect.log"

[Nodes]
NodesFile = "/tmp/nodes.db"
Api = "http://<url>/allnodes"
RequestTimeout = 5
ConnectonTimeout = 1 
MaxAge = 30
AutoUpdate = false

[CSSH]
Enable = false
Path = "/usr/bin/csshX"

