[General]
LogFile = "/tmp/go_connect.log"

[Nodes]
NodesFile = "/Users/jorge.flores/nodes.db"
Api = "http://chef.zenvia360.com:4567/allnodes"
RequestTimeout = 5
ConnectonTimeout = 1 
MaxAge = 30
AutoUpdate = false

[CSSH]
Enable = false
Path = "/Users/jorge.flores/csshx/csshX"

